# Use custom format:
format="$directory$git_branch$character"

# Prompt symbols 
[character]
success_symbol = "[🞈](bright-green bold)"
error_symbol = "[🞈](bright-red)"
vicmd_symbol = "[🞈](bright-yellow)"

[directory]
format = "[]($style)[(bg:white fg:black)$path](bg:white fg:black)[ ]($style)"
style = "bg:background fg:white"

[git_branch]
format = "[]($style)[[ ](bg:white fg:black bold)$branch](bg:white fg:black)[ ]($style)"
style = "bg:background fg:white"